#
# Copyright (C) 2012 Samsung Electronics
# Lukasz Majewski <l.majewski@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

#UBOOTINCLUDE_TEMP = $(UBOOTINCLUDE)
#UBOOTINCLUDE	+= -I$(SRCTREE)/board/bananapi/include

obj-y += bpir2_cmd.o


#$(warning ====================================================================)
#$(warning $(SRCTREE))
#$(warning $(OBJTREE))
#$(warning $(UBOOTINCLUDE))
#$(warning $(ARCH))
#$(warning $(BOARD))
#$(warning ====================================================================)

